apiVersion : apps/v1
kind: Deployment
metadata:
  name: "myakscluster-1bb1"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "myakscluster-1bb1"
  template:
    metadata:
      labels:
        app: "myakscluster-1bb1"
    spec:
      containers:
        - name: "myakscluster-1bb1"
          image: "myacr9999.azurecr.io/myakscluster"
          ports:
          - containerPort: 80