apiVersion : apps/v1
kind: Deployment
metadata:
  name: "myaskcluster1-6089"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "myaskcluster1-6089"
  template:
    metadata:
      labels:
        app: "myaskcluster1-6089"
    spec:
      containers:
        - name: "myaskcluster1-6089"
          image: "myacr2022s.azurecr.io/myaskcluster1"
          ports:
          - containerPort: 80