apiVersion : apps/v1
kind: Deployment
metadata:
  name: "myakscluster-6309"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "myakscluster-6309"
  template:
    metadata:
      labels:
        app: "myakscluster-6309"
    spec:
      containers:
        - name: "myakscluster-6309"
          image: "mydockerapp2023.azurecr.io/myakscluster"
          ports:
          - containerPort: 80