apiVersion : apps/v1
kind: Deployment
metadata:
  name: "myakscluster-c9be"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "myakscluster-c9be"
  template:
    metadata:
      labels:
        app: "myakscluster-c9be"
    spec:
      containers:
        - name: "myakscluster-c9be"
          image: "azure2aksacr.azurecr.io/myakscluster"
          ports:
          - containerPort: 80