apiVersion : apps/v1
kind: Deployment
metadata:
  name: "myaks-2c35"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "myaks-2c35"
  template:
    metadata:
      labels:
        app: "myaks-2c35"
    spec:
      containers:
        - name: "myaks-2c35"
          image: "myacrs2025.azurecr.io/myaks"
          ports:
          - containerPort: 80