apiVersion : apps/v1
kind: Deployment
metadata:
  name: "myaks-a2c4"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "myaks-a2c4"
  template:
    metadata:
      labels:
        app: "myaks-a2c4"
    spec:
      containers:
        - name: "myaks-a2c4"
          image: "myacr202207.azurecr.io/myaks"
          ports:
          - containerPort: 80