apiVersion: v1
kind: Service
metadata:
    name: "myaskcluster1-6089"
    labels:
        app: "myaskcluster1-6089"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "myaskcluster1-6089"