on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: myacr2022s.azurecr.io
        username: ${{ secrets.acr_myacr2022s_username }}
        password: ${{ secrets.acr_myacr2022s_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t myacr2022s.azurecr.io/myaskcluster1:${{ github.sha }} --label dockerfile-path=Dockerfile
        docker push myacr2022s.azurecr.io/myaskcluster1:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_myaskcluster1_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep myaskcluster1b151-dotnetapp | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace myaskcluster1b151-dotnetapp`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: myaskcluster1b151-dotnetapp
        container-registry-url: myacr2022s.azurecr.io
        container-registry-username: ${{ secrets.acr_myacr2022s_username }}
        container-registry-password: ${{ secrets.acr_myacr2022s_password }}
        secret-name: myaskclusterdockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: myaskcluster1b151-dotnetapp
        manifests: |
          manifests/deployment-6.yml
          manifests/service-6.yml
        images: |
          myacr2022s.azurecr.io/myaskcluster1:${{ github.sha }}
        imagepullsecrets: |
          myaskclusterdockerauth
