on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: myacr202210.azurecr.io
        username: ${{ secrets.acr_myacr202210_username }}
        password: ${{ secrets.acr_myacr202210_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t myacr202210.azurecr.io/myaks:${{ github.sha }} --label dockerfile-path=Dockerfile
        docker push myacr202210.azurecr.io/myaks:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_myaks_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep myaksb919-helloworld | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace myaksb919-helloworld`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: myaksb919-helloworld
        container-registry-url: myacr202210.azurecr.io
        container-registry-username: ${{ secrets.acr_myacr202210_username }}
        container-registry-password: ${{ secrets.acr_myacr202210_password }}
        secret-name: myaksdockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: myaksb919-helloworld
        manifests: |
          manifests/deployment-13.yml
          manifests/service-13.yml
        images: |
          myacr202210.azurecr.io/myaks:${{ github.sha }}
        imagepullsecrets: |
          myaksdockerauth
