on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: azure2aksacr.azurecr.io
        username: ${{ secrets.acr_azure2aksacr_username }}
        password: ${{ secrets.acr_azure2aksacr_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t azure2aksacr.azurecr.io/myakscluster:${{ github.sha }} --label dockerfile-path=Dockerfile
        docker push azure2aksacr.azurecr.io/myakscluster:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_myakscluster_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep myakscluster902a-dotnet | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace myakscluster902a-dotnet`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: myakscluster902a-dotnet
        container-registry-url: azure2aksacr.azurecr.io
        container-registry-username: ${{ secrets.acr_azure2aksacr_username }}
        container-registry-password: ${{ secrets.acr_azure2aksacr_password }}
        secret-name: myaksclusterdockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: myakscluster902a-dotnet
        manifests: |
          manifests/deployment-7.yml
          manifests/service-7.yml
        images: |
          azure2aksacr.azurecr.io/myakscluster:${{ github.sha }}
        imagepullsecrets: |
          myaksclusterdockerauth
